### ISSUE TITLE
App doesn't startup, and no log is shown

### ISSUE THREAD

**Issue by soumyaDghosh** [linuxmint/hypnotix#277]
Hello, I have snapped this app, but it doesn't showup, and doesn't show any error log. This is the `snapcraft.yaml`

```
name: hypnotix
version: '3.2'
base: core22
icon: snap/hypnotix.svg
summary: IPTV player for M3U playlists
description: |
  Hypnotix is an IPTV streaming application with support for live TV, movies and series.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
layout:
  /usr/lib/hypnotix:
    bind: $SNAP/usr/lib/hypnotix
parts:
  hypnotix:
    source: https://github.com/linuxmint/hypnotix.git
    plugin: dump
    stage-packages:
      - gir1.2-xapp-1.0
      - libxapp1
      - python3-imdbpy
      - libmpv1
      - python3-requests
      - xapps-common
    prime:
      - usr/*
apps:
  hypnotix:
    command: usr/bin/hypnotix
    extensions: [ gnome ]
    desktop: usr/share/applications/hypnotix.desktop
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      
```
